### ISSUE TITLE
Breaks Redux ideology - action creators don't dispatch actions

### ISSUE THREAD

**Issue by dougrday** [nathan-rice/radical#2]
Ideally, action creators shouldn't dispatch actions within (unless they're specifically a thunk).  Instead, they should return a POCO json object.  This allows you to really leverage the power of middleware better.

**Comment by nathan-rice** [comment]
I'm more concerned with clarity and ease of use than ideology.  That being said, if you can provide some examples of where using Radical prevents/interferes with using Redux middleware, I'll be happy to look at them and try to address the issue.

**Comment by dougrday** [comment]
For example, take the [redux-validator](https://www.npmjs.com/package/redux-validator) library.

To add validation to an action, it needs JSON added to it.  Something like this:

```
{
    meta: {
        validator: {
            target: {
                func: (text, state, payload) => 0 < text.length,
                msg: 'Target cannot be empty.'
            },
        }
    }
}
```

So, generally I'd make an action creator that wraps an existing action with validation information:

```
function createValidator(action, validator) {
    return Object.assign({}, action, {
        meta: {
            validator
        }
    });
}
```

Given your example on the home page, you'd have to use this action creator directly within your code:

```
// For this action I'll specify the reducer manually.
    var setTarget = Radical.Action.create({
        initiator: function (action, newTarget) {
            var validator = { 
                target: {
                    func: (text, state, payload) => 0 < text.length,
                    msg: 'Target cannot be empty.'
                }
            }
            return action.dispatch(createValidator({target: newTarget}, validator);
        }
    }
```

While this option has some implications (like, how you might [localize](https://en.wikipedia.org/wiki/Internationalization_and_localization) it), it forces you to couple the validation logic with your implementation.  If you wanted to abstract the validation logic away to another area of the application, it's virtually impossible because you're dispatch()ing the actions immediately.

Here's the Redux docs regarding the subject:  http://redux.js.org/docs/basics/Actions.html

Note the text (emphasis added):

> In Redux action creators simply return an action:
> 
> ```
> function addTodo(text) {
>   return {
>     type: ADD_TODO,
>     text
>   }
> }
> ```
> 
> **This makes them portable and easy to test.**
> 
> In traditional Flux action creators often trigger a dispatch when invoked...
> In Redux this is **not** the case.

I'm not saying you can drastically change your application to fix this issue.  On the contrary, I think it is what it is.  I'm pointing out the design issue that prevents **me** from being able to choose it for development.

Anyhow, thanks for lending an ear :)

**Comment by dougrday** [comment]
As an aside - I'd be interested to see how your library interacts with [redux-thunk](https://github.com/gaearon/redux-thunk).  Have you tested various redux middlewares to see how they interact?
